name: Deploy React App to GitHub Pages

on:
  push:
    branches: ["main"]     # Trigger on push to main branch
  workflow_dispatch:       # Allow manual run in Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'     # Use a Node.js version as you prefer

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build         # The output folder from npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-pages.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-pages-artifact@v1

      - name: Deploy to GitHub Pages
        id: deploy-to-pages
        uses: actions/deploy-pages@v1
